parameters:
    form.simple_handler.http_code_key: __code

services:

    form.simple_handler:
        class: Splot\FrameworkExtraModule\Form\SimpleHandler
        arguments:
            - @knit
            - %form.simple_handler.http_code_key%
