parameters:

    form.simple_handler.http_code_key: __code

    filestorage.simple.parent_dir: %web_dir%
    filestorage.simple.dir: /filestorage/

services:

    process: Splot\FrameworkExtraModule\Process\Process
    imaging: Splot\FrameworkExtraModule\Imaging\Imaging

    controller.request_injector:
        class: Splot\FrameworkExtraModule\Controller\RequestInjector
        arguments:
            - @router
            - @request
        notify:
            - ["@event_manager", "subscribeService", ["%event.controller_will_respond%", "@=", "injectRequest"]]

    form.simple_handler:
        class: Splot\FrameworkExtraModule\Form\SimpleHandler
        arguments:
            - @knit
            - %form.simple_handler.http_code_key%

    filestorage.simple:
        class: Splot\FrameworkExtraModule\FileStorage\SimpleStorage
        arguments:
            - @filesystem
            - %filestorage.simple.parent_dir%
            - %filestorage.simple.dir%
